### ISSUE TITLE
insert and ordering

### ISSUE THREAD

**Issue by wolpers** [usecanvas/logoot-js#1]
Hi, I was wondering, would the following be possible?  

```
[
  [[[[0, 0]], 0], null],
  [[[[0, 0],[1, 0]], 2], "xxx"],    // or:  [[[[0, 0],[0, 0]], 2], "xxx"], ?
  [[[[1, 1]], 0], ""],
  [[[[32767, 0]], 1], null]
]
```

And can anything be added above the 'xxx' atom?

**Comment by jclem** [comment]
In the first case, the new atom should be:

```
[
  [[[0, 0]], 0], null],
  [[[0, 0], [0, siteID]], 1], "new line"],
  [[[0, 0], [1, 0]], 2], "xxx"],
  // etc.
]
```

The [Elixir implementation](https://github.com/usecanvas/logoot_ex) handles this fine, but this implementation doesn't, so that's a bug.

It's not possible to create the other identifier you specify, since in your example `0` is the minimal identifier for the `null` site. It does not create atoms other than the start and end atoms. A realistic similar atom would be `[[[0, 0], [0, 1]], 2], "xxx"]`. An atom that precedes this one would be `[[[0, 0], [0, 0], [14552, 5]], 1], "aaa"]`.

**Comment by jclem** [comment]
Leaving this open for discussion if you'd like to reply. The bug, however, is fixed by ef4aadb.

**Comment by wolpers** [comment]
Ah, so the zero siteID is reserved for generating the endpoints. And any other site can prepend [0, 0] identifiers, as long as the last inserted identifier in an atom has the proper siteID.  If that is correct there is no problem when one keeps inserting at the top, even using zero positions.  I was afraid that there was the theoretical possibility of a dead end here where one would not be able to insert anything above a certain atom any more.
So the following steps would work for site one (or any site but site zero), if that site keeps inserting at the top.  Right?     

```
[
  [[[0, 0]], 0], null],
  [[[[32767, 0]], 1], null]
]

[
  [[[0, 0]], 0], null],
  [[[0, 1]], 0], "a"],
  [[[[32767, 0]], 1], null]
]

[
  [[[0, 0]], 0], null],
  [[[0, 0], [0, 1]], 1], "b"],
  [[[0, 1]], 0], "a"],
  [[[[32767, 0]], 1], null]
]

[
  [[[0, 0]], 0], null],
  [[[0, 0], [0, 0], [0, 1]], 2], "c"],
  [[[0, 0], [0, 1]], 1], "b"],
  [[[0, 1]], 0], "a"],
  [[[[32767, 0]], 1], null]
]
```

**Comment by jclem** [comment]
Theoretically, yes. However, the second step in your example would not happen in this implementation. Because 32767 - 0 > 1, we choose a random number between the two, so you're more likely to get something like:

```
[
  [[[0, 0]], 0], null],
  [[[1643, 1]], 0], "a"],
  [[[[32767, 0]], 1], null]
]
```

Now let's say you got very unlucky and you ended up with this, instead:

```
[
  [[[0, 0]], 0], null],
  [[[1, 1]], 0], "a"],
  [[[[32767, 0]], 1], null]
]
```

If we needed to insert something between the first and second lines here, we'd prefix with `[0, 0]`, but are then free to choose a random number from the full range:

```
[
  [[[0, 0]], 0], null],
  [[[0, 0], [12549, 1]], 1], "x"],
  [[[1, 1]], 0], "a"],
  [[[[32767, 0]], 1], null]
]
```

**Comment by wolpers** [comment]
Thank's for your help here.  I just could not get my head around this, until now.

**Comment by jclem** [comment]
You're welcome!
